/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in initialized apps.
// It is kept here so TypeScript can understand Next-specific imports before
// the full application scaffold is built.
